kind: pipeline
type: docker
name: test
steps:
  - name: test
    image: golang
    volumes:
      - name: deps
        path: /go
    commands:
      - go test

---
kind: pipeline
type: docker
name: build
trigger:
  event:
    exclude:
      - custom
steps:
  - name: build
    image: golang
    volumes:
      - name: deps
        path: /go
    commands:
      - go build

---
kind: pipeline
type: docker
name: coverage
depends_on:
  - test
  - build
trigger:
  event:
    - custom
steps:
  - name: coverage
    image: golang
    volumes:
      - name: deps
        path: /go
    commands:
      - go test ./... -coverprofile=coverage.out && go tool cover -html=coverage.out -o coverage.html

volumes:
  - name: deps
    temp: {}
