kind: pipeline
type: docker
name: test

steps:
  - name: test
    image: golang
    commands:
      - go test

---
kind: pipeline
type: docker
name: build
steps:
  - name: build
    image: golang
    commands:
      - go build
